os:
    - linux
    - osx

matrix:
    allow_failures:
        #- os: osx

language: go

go:
    - 1.0
    - 1.1
    - 1.2
    - 1.3
    - 1.4
    - 1.5
    - 1.6

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make unittest; fi
    - make test-version
    - make test-standard
    - make test-monochrome
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make all-archs; fi

notifications:
    email: false
