os:
    - linux
    - osx

matrix:
    allow_failures:
        - os: osx

language: go

go:
    - 1.6

script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make unittest; fi
    - make test
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make all-archs; fi

notifications:
    email: false
