os:
    - linux
    - osx

matrix:
    allow_failures:
        - os: osx

language: go

go:
    - 1.6

script:
    - make unittest
    - make all-archs
    - make test

notifications:
    email: false
