version: 1.0.{build}

configuration:
  - Release

platform:
  - x64
  - x86

build_script:
- cmd: >-
    python -V

    go version

    python build.py --build

test_script:
- cmd: >-
    bin\havenet.exe -V

    bin\havenet.exe

    bin\havenet.exe -6
